### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by eugene-chow**
Updated READMEs for the repo and the `virtual-cluster` mission. @CloudCommandos/infra please learn how git and PRs work because you'll be using it a lot in the future.

Each of you please leave a review and approve the PR.

### CODE REVIEW

**Review by jiunnyuan1991 — COMMENTED** [review]
Awesome

**Review by alexling92 — APPROVED** [review]
Great :)

**Review by youngee91 — APPROVED** [review]
Roger that

**Review by jiunnyuan1991 — APPROVED** [review]

**Comment by eugene-chow** [comment]
I find your enthusiasm encouraging :) Ok now that you guys know how it works. Let's do this PR thingy when you check in your docs/code.

**Pull request merged**
